- name: Add github runner user
  ansible.builtin.user:
    name: github-runner
    home: /github-runner
    shell: /bin/bash

- name: Download runner software
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
    dest: /github-runner
    owner: github-runner
    group: github-runner
    remote_src: yes

- name: Setup Nodejs Module
  ansible.builtin.shell: |
    dnf module disable nodejs -y
    dnf module enable nodejs:20 -y

- name: Install libicu
  ansible.builtin.dnf:
    name: libicu
    state: installed

- name: Configure runner
  ansible.builtin.shell: |
   ./config.sh --url https://github.com/DevopsSudhir0609 --token BKAGGIO77OZJ7A235ZZZV4DIH3YRA
  args:
    chdir: /github-runner
  become: true
  become_user: github-runner

- name: Install runner service
  ansible.builtin.shell: |
    ./svc.sh install
  args:
    chdir: /github-runner
  become: true
  become_user: github-runner

- name: Deploy GitHub Runner systemd service
  ansible.builtin.template:
    src: github-runner.service.j2
    dest: /etc/systemd/system/github-runner.service
    owner: root
    group: root
    mode: '0644'
  notify: restart github runner

- name: Setup Docker repo
  ansible.builtin.template:
    src: docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo

- name: Add user to docker group
  ansible.builtin.user:
    name: github-runner
    groups: docker
    append: yes

- name: Start and enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop:
    - docker
    - github-runner

- name: Install Terraform
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
  register: hashicorp_repo

- name: Install Terraform package
  ansible.builtin.dnf:
    name: terraform
    state: present
  when: hashicorp_repo.changed

- name: Install Sonar Scanner
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
    dest: /opt
    remote_src: yes

- name: ACR login
  ansible.builtin.shell: |
    az acr login --name "{{ acr_name }}" --expose-token | jq -r '.accessToken' | docker login "{{ acr_name }}.azurecr.io" --username "{{ acr_name }}" --password-stdin
  args:
    chdir: /github-runner
  become: true
  become_user: github-runner
  when: acr_name is defined

# Handlers section moved outside the main tasks list
- name: Start Service
  ansible.builtin.systemd_service:
    name: github-runner
    state: restarted
    enabled: yes
    daemon-reload: yes
