-name: install vault
ansible.builtin.get_url:
 url: https://releases.hashicorp.com/RHEL/hashicorp.repo
 dest: /etc/yum.repos.d/hashicorp.repo


-name: install vault
ansible.builtin.dnf:
 name: vault
 state: installed


-name: copy vault config file
ansible.builtin.copy:
src: vault.hcl
dest: /etc/vault.d/vault.hcl

-name: start vault
ansible.builtin.systemd_service:
name: vault
state: started
enabled: yes

